import { Lead } from '../types/lead';

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-001',
    fullName: 'Jessica Miller',
    profession: 'real_estate',
    professionTitle: 'Licensed Real Estate Salesperson',
    state: 'CA',
    city: 'San Diego',
    licenseNumber: 'CA-RE-02194812',
    issueDate: '2026-08-14',
    collegeOrSchool: 'UC San Diego Real Estate Academy',
    graduationYear: 2026,
    licenseStatus: 'Newly Issued',
    skipTraceStatus: 'Traced',
    skipTraceData: {
      tracedAt: '2026-08-15T10:30:00Z',
      confidenceScore: 98,
      verifiedPhone: '+1 (619) 555-0182',
      phoneType: 'Mobile (AT&T Mobility)',
      dncStatus: 'Clean - Not on DNC List',
      primaryEmail: 'jessica.miller.realty@gmail.com',
      emailValidation: 'Valid & Deliverable (99% Score)',
      secondaryEmail: 'jessica@millersd properties.com',
      linkedInUrl: 'linkedin.com/in/jessicamiller-sd-realtor',
      instagramHandle: '@jessicamiller_realty',
      currentAddress: '4520 Ocean Blvd, Suite 300, San Diego, CA 92109',
      enrichmentNotes: 'Passed CA DRE exam on Aug 12, 2026. High intent to launch personal brand website.',
    },
    outreachStatus: 'Site Built',
    websiteConfig: {
      templateId: 'realty_pro',
      heroHeadline: 'Modern Coastal Living in San Diego',
      heroSubheadline: 'Helping buyers & sellers navigate San Diego real estate with local expertise and personalized care.',
      bioText: 'Jessica Miller is a newly licensed San Diego real estate specialist dedicated to helping clients find their dream coastal home.',
      tagline: 'Your Trusted San Diego Real Estate Advisor',
      primaryColor: '#0f766e',
      accentColor: '#f59e0b',
      offerPrice: 1000,
      previewSlug: 'jessicamiller-realty',
      callToAction: 'Schedule Free Property Consultation',
      demoPhotos: [
        'https://picsum.photos/seed/realestate1/800/600',
        'https://picsum.photos/seed/realestate2/800/600',
      ],
      services: [
        {
          id: 's1',
          title: 'First-Time Homebuyers',
          description: 'Step-by-step guidance from pre-approval to closing key handover.',
          iconName: 'Home',
        },
        {
          id: 's2',
          title: 'Home Seller Valuation',
          description: 'Comprehensive comparative market analysis to maximize your home value.',
          iconName: 'TrendingUp',
        },
        {
          id: 's3',
          title: 'Coastal Neighborhood Tours',
          description: 'Insider knowledge on San Diego coastal micro-markets and schools.',
          iconName: 'Compass',
        },
      ],
    },
    outreachLogs: [],
    estimatedDealValue: 1000,
    createdAt: '2026-08-15T08:00:00Z',
  },
  {
    id: 'lead-002',
    fullName: 'Dr. Marcus Sterling, DPT',
    profession: 'therapy',
    professionTitle: 'Licensed Physical Therapist',
    state: 'TX',
    city: 'Austin',
    licenseNumber: 'TX-PT-883921',
    issueDate: '2026-08-18',
    collegeOrSchool: 'University of Texas Medical Branch',
    graduationYear: 2026,
    licenseStatus: 'Active Board Pass',
    skipTraceStatus: 'Traced',
    skipTraceData: {
      tracedAt: '2026-08-19T14:15:00Z',
      confidenceScore: 95,
      verifiedPhone: '+1 (512) 555-0941',
      phoneType: 'Mobile (Verizon Wireless)',
      dncStatus: 'Clean - Not on DNC List',
      primaryEmail: 'marcus.sterling.dpt@gmail.com',
      emailValidation: 'Valid & Deliverable (97% Score)',
      linkedInUrl: 'linkedin.com/in/marcussterling-dpt',
      instagramHandle: '@sterling_pt_austin',
      currentAddress: '1100 Congress Ave, Austin, TX 78701',
      enrichmentNotes: 'Graduated DPT Class of 2026. Opening mobile physical therapy & sports recovery clinic.',
    },
    outreachStatus: 'Outreach Sent',
    websiteConfig: {
      templateId: 'care_nurse',
      heroHeadline: 'Austin Mobile Physical Therapy & Sports Recovery',
      heroSubheadline: 'Personalized 1-on-1 rehab, injury recovery, and athletic performance therapy brought directly to your door.',
      bioText: 'Dr. Marcus Sterling holds a Doctorate in Physical Therapy and specializes in movement optimization and sports injury rehabilitation in Austin, TX.',
      tagline: 'Move Without Pain. Perform Without Limits.',
      primaryColor: '#2563eb',
      accentColor: '#10b981',
      offerPrice: 1000,
      previewSlug: 'sterling-performance-pt',
      callToAction: 'Book Your Initial Assessment',
      demoPhotos: [
        'https://picsum.photos/seed/rehab1/800/600',
        'https://picsum.photos/seed/rehab2/800/600',
      ],
      services: [
        {
          id: 's1',
          title: 'Concierge Mobile Therapy',
          description: 'In-home or office rehab sessions tailored around your busy schedule.',
          iconName: 'Activity',
        },
        {
          id: 's2',
          title: 'Sports Injury Rehab',
          description: 'Evidence-based protocols to get athletes safely back into peak performance.',
          iconName: 'Zap',
        },
        {
          id: 's3',
          title: 'Post-Op Rehabilitation',
          description: 'Dedicated post-surgical recovery plans with continuous progress tracking.',
          iconName: 'ShieldCheck',
        },
      ],
    },
    outreachLogs: [
      {
        id: 'log-1',
        timestamp: '2026-08-20T11:00:00Z',
        type: 'email',
        subject: 'Congrats on passing your PT License, Dr. Sterling! (Pre-built website preview)',
        content: 'Hi Marcus, Congratulations on receiving your Physical Therapy license in Texas! We built a custom mobile PT landing page for you: sterling-performance-pt.licensify.app',
        status: 'opened',
        toneUsed: 'Warm & Congratulatory',
      },
    ],
    estimatedDealValue: 1000,
    createdAt: '2026-08-18T09:30:00Z',
  },
  {
    id: 'lead-003',
    fullName: 'Sophia Ramirez, RN',
    profession: 'nursing',
    professionTitle: 'Registered Nurse (BSN, RN)',
    state: 'FL',
    city: 'Miami',
    licenseNumber: 'FL-RN-994102',
    issueDate: '2026-08-20',
    collegeOrSchool: 'University of Miami School of Nursing',
    graduationYear: 2026,
    licenseStatus: 'Newly Issued',
    skipTraceStatus: 'Traced',
    skipTraceData: {
      tracedAt: '2026-08-21T09:00:00Z',
      confidenceScore: 96,
      verifiedPhone: '+1 (305) 555-0318',
      phoneType: 'Mobile (T-Mobile)',
      dncStatus: 'Clean - Not on DNC List',
      primaryEmail: 'sophia.ramirez.rn@gmail.com',
      emailValidation: 'Valid (98% Score)',
      linkedInUrl: 'linkedin.com/in/sophiaramirez-rn',
      instagramHandle: '@miamicaretake_rn',
      currentAddress: '801 Brickell Ave, Miami, FL 33131',
      enrichmentNotes: 'Passed NCLEX-RN Aug 2026. Launching private IV therapy & post-op concierge nursing.',
    },
    outreachStatus: 'In Discussion',
    websiteConfig: {
      templateId: 'care_nurse',
      heroHeadline: 'Miami VIP Concierge Nursing & IV Hydration',
      heroSubheadline: 'Private registered nurse care, post-surgical recovery, and wellness hydration treatments in Miami.',
      bioText: 'Sophia Ramirez, BSN, RN provides discreet, high-touch private nursing services for recovery and wellness clients across South Florida.',
      tagline: 'Compassionate Care. Ultimate Privacy.',
      primaryColor: '#e11d48',
      accentColor: '#06b6d4',
      offerPrice: 1000,
      previewSlug: 'sophiaramirez-concierge-rn',
      callToAction: 'Inquire About Private Nursing',
      demoPhotos: [
        'https://picsum.photos/seed/nursing1/800/600',
        'https://picsum.photos/seed/nursing2/800/600',
      ],
      services: [
        {
          id: 's1',
          title: 'Post-Op Recovery Support',
          description: 'Specialized cosmetic & surgical recovery monitoring in your private residence or hotel.',
          iconName: 'HeartPulse',
        },
        {
          id: 's2',
          title: 'Custom IV Wellness Drips',
          description: 'Electrolyte, immunity, and glow infusions administered by a certified RN.',
          iconName: 'Sparkles',
        },
        {
          id: 's3',
          title: 'Private Health Monitoring',
          description: 'Regular vital checks, medication administration, and physician updates.',
          iconName: 'Shield',
        },
      ],
    },
    outreachLogs: [
      {
        id: 'log-2',
        timestamp: '2026-08-22T14:30:00Z',
        type: 'email',
        subject: 'Congrats on your RN license, Sophia! Preview your Miami Concierge site',
        content: 'Hi Sophia, Huge congrats on passing the NCLEX! Check out the site preview we set up for your IV & concierge practice.',
        status: 'clicked',
        toneUsed: 'Professional & Authoritative',
      },
    ],
    estimatedDealValue: 1000,
    createdAt: '2026-08-20T11:00:00Z',
  },
  {
    id: 'lead-004',
    fullName: 'Brandon Hayes, Esq.',
    profession: 'legal',
    professionTitle: 'Licensed Attorney at Law',
    state: 'NY',
    city: 'New York',
    licenseNumber: 'NY-BAR-591028',
    issueDate: '2026-08-05',
    collegeOrSchool: 'Columbia Law School',
    graduationYear: 2026,
    licenseStatus: 'Active Board Pass',
    skipTraceStatus: 'Traced',
    skipTraceData: {
      tracedAt: '2026-08-06T16:00:00Z',
      confidenceScore: 99,
      verifiedPhone: '+1 (212) 555-0732',
      phoneType: 'Mobile (AT&T Wireless)',
      dncStatus: 'Clean - Not on DNC List',
      primaryEmail: 'brandon@hayeslawny.com',
      emailValidation: 'Valid (100% Score)',
      linkedInUrl: 'linkedin.com/in/brandonhayes-esq',
      currentAddress: '350 Fifth Ave, Floor 42, New York, NY 10118',
      enrichmentNotes: 'Passed NY Bar Exam 2026. Specializing in startup incorporation, IP law, and tech founder counsel.',
    },
    outreachStatus: 'Client Won',
    websiteConfig: {
      templateId: 'legal_counsel',
      heroHeadline: 'Strategic Legal Counsel for New York Founders & Tech Startups',
      heroSubheadline: 'Protecting innovation, structuring early-stage ventures, and negotiating agreements with clarity.',
      bioText: 'Brandon Hayes, Esq. is a New York licensed attorney advising tech startups, creator businesses, and emerging enterprises.',
      tagline: 'Modern Legal Solutions for Ambitious Founders',
      primaryColor: '#1e293b',
      accentColor: '#d97706',
      offerPrice: 1200,
      previewSlug: 'hayeslaw-ny',
      callToAction: 'Book 20-Min Legal Discovery Call',
      demoPhotos: [
        'https://picsum.photos/seed/legal1/800/600',
        'https://picsum.photos/seed/legal2/800/600',
      ],
      services: [
        {
          id: 's1',
          title: 'Startup Formation & Incorporation',
          description: 'Delaware C-Corp setup, founder vesting schedules, and equity agreements.',
          iconName: 'FileText',
        },
        {
          id: 's2',
          title: 'Commercial Contracts & Terms',
          description: 'SaaS agreements, privacy policies, master service agreements, and vendor contracts.',
          iconName: 'Scale',
        },
        {
          id: 's3',
          title: 'Trademark & IP Protection',
          description: 'Comprehensive USPTO trademark filing and IP assignment agreements.',
          iconName: 'Lock',
        },
      ],
    },
    outreachLogs: [
      {
        id: 'log-3',
        timestamp: '2026-08-10T09:00:00Z',
        type: 'email',
        subject: 'Congrats on passing the NY Bar, Brandon! Quick website question',
        content: 'Hi Brandon, Passed the bar! Built a modern law firm landing page demo for your practice: hayeslaw-ny.licensify.app',
        status: 'responded',
        toneUsed: 'Direct & High Converting',
      },
    ],
    estimatedDealValue: 1200,
    createdAt: '2026-08-05T12:00:00Z',
  },
  {
    id: 'lead-005',
    fullName: 'Chloe Laurent',
    profession: 'beauty',
    professionTitle: 'Licensed Medical Esthetician',
    state: 'GA',
    city: 'Atlanta',
    licenseNumber: 'GA-EST-30912',
    issueDate: '2026-08-17',
    collegeOrSchool: 'Atlanta Institute of Aesthetics',
    graduationYear: 2026,
    licenseStatus: 'Newly Issued',
    skipTraceStatus: 'Traced',
    skipTraceData: {
      tracedAt: '2026-08-18T11:20:00Z',
      confidenceScore: 94,
      verifiedPhone: '+1 (404) 555-0629',
      phoneType: 'Mobile (Verizon)',
      dncStatus: 'Clean - Not on DNC List',
      primaryEmail: 'chloe.skin.atl@gmail.com',
      emailValidation: 'Valid (96% Score)',
      instagramHandle: '@chloelaurent_skin',
      currentAddress: '3393 Peachtree Rd NE, Atlanta, GA 30326',
      enrichmentNotes: 'Licensed Esthetician in Georgia. Opening suite in Buckhead Atlanta for custom skincare.',
    },
    outreachStatus: 'Skip Traced',
    websiteConfig: {
      templateId: 'studio_beauty',
      heroHeadline: 'Luminous Skin & Advanced Facial Studio in Buckhead',
      heroSubheadline: 'Bespoke skincare treatments, chemical peels, and holistic facial therapy for effortless radiance.',
      bioText: 'Chloe Laurent is a licensed medical esthetician specializing in personalized barrier repair and glass-skin glow treatments.',
      tagline: 'Elevate Your Natural Glow',
      primaryColor: '#db2777',
      accentColor: '#fb7185',
      offerPrice: 1000,
      previewSlug: 'chloelaurent-skinstudio',
      callToAction: 'Book Skin Consultation',
      demoPhotos: [
        'https://picsum.photos/seed/beauty1/800/600',
        'https://picsum.photos/seed/beauty2/800/600',
      ],
      services: [
        {
          id: 's1',
          title: 'Custom Hydro-Glow Facial',
          description: 'Deep pore cleansing, exfoliation, and antioxidant hydration infusion.',
          iconName: 'Sparkles',
        },
        {
          id: 's2',
          title: 'Acne & Barrier Therapy',
          description: 'Targeted protocols to soothe inflammation and restore skin barrier balance.',
          iconName: 'CheckCircle',
        },
        {
          id: 's3',
          title: 'Dermaplaning & Lash Tinting',
          description: 'Gentle peach fuzz removal paired with custom lash definition.',
          iconName: 'Eye',
        },
      ],
    },
    outreachLogs: [],
    estimatedDealValue: 1000,
    createdAt: '2026-08-17T15:00:00Z',
  },
  {
    id: 'lead-006',
    fullName: 'Tyler Vance',
    profession: 'trade',
    professionTitle: 'Licensed Electrical Contractor',
    state: 'IL',
    city: 'Chicago',
    licenseNumber: 'IL-LEC-99201',
    issueDate: '2026-08-22',
    collegeOrSchool: 'Chicago Electrical Trades Union Academy',
    graduationYear: 2026,
    licenseStatus: 'Newly Issued',
    skipTraceStatus: 'Not Traced',
    outreachStatus: 'Uncontacted',
    outreachLogs: [],
    estimatedDealValue: 1200,
    createdAt: '2026-08-22T08:15:00Z',
  },
  {
    id: 'lead-007',
    fullName: 'David K. Chen, CPA',
    profession: 'finance',
    professionTitle: 'Certified Public Accountant',
    state: 'WA',
    city: 'Seattle',
    licenseNumber: 'WA-CPA-772910',
    issueDate: '2026-08-23',
    collegeOrSchool: 'University of Washington Foster School of Business',
    graduationYear: 2026,
    licenseStatus: 'Active Board Pass',
    skipTraceStatus: 'Not Traced',
    outreachStatus: 'Uncontacted',
    outreachLogs: [],
    estimatedDealValue: 1200,
    createdAt: '2026-08-23T10:45:00Z',
  },
];
